FROM node:22.17.1-alpine AS dependencies
WORKDIR /app

# Устанавливаем pnpm
RUN npm install -g pnpm@10.13.1

# Копируем файлы зависимостей
COPY package.json ./
COPY pnpm-lock.yaml ./

# Устанавливаем все зависимости
RUN pnpm install --frozen-lockfile

# Копируем всё остальное
COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "dev"]